services:
  bot:
    build: .
    image: tgibot:latest
    container_name: telegram-interactive-bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENV_FILE_PATH=/app/.env
